### ISSUE TITLE
entity property with HasConversion failed

### ISSUE THREAD

**Issue by ngvtien** [neisbut/Npgsql.Bulk#35]
Say for instance if there is a conversion on the property 

eg: Converting array into Json object in the database like the example below

modelBuilder.Entity<Draft>()
            .Property(p => p.Cc)
            .HasConversion(v => JsonConvert.SerializeObject(v),
                            c => JsonConvert.DeserializeObject<Participant[]>(c));
modelBuilder.Entity<Draft>()
            .Property(p => p.From)
            .HasConversion(v => JsonConvert.SerializeObject(v),
                            c => JsonConvert.DeserializeObject<Participant[]>(c));

this library will crash with exception:
"Can't write CLR type System.String[] to database type text" 

Which I know why but can't seems to get reflection code to write these value out

**Comment by neisbut** [comment]
Hi @ngvtien, thanks for reporting this. I will check soon.

**Comment by ngvtien** [comment]
Hi Anton,

I have a working version but didn't use reflection to emit as I am
well-versed and felt it would be hard to maintain over time.

Is it possible to have a version without reflection emit.

Also with updating properties can it be default to all fields except for
ids and unique constraints fields and if so you don't need to provide that
parameter?

Regards,

**Comment by neisbut** [comment]
Hi @ngvtien, sorry for such a late answer. Actually I feel the same about using code generation, so started to use it less, espcially for EF Core version. It is mostly because EF Core has so many features and I'm trying to support all of them. Unfortuntelly currently I don't have enough time to do a proper refactoring.
Thanks for suggestion about updating properties, will try to implement it one day.
Btw, HasConversion should be supported now in a latest version. Please try when possible.

**Comment by neisbut** [comment]
Closed due to inactivity
