### ISSUE TITLE
enum doesn't work

### ISSUE THREAD

**Issue by erwan-joly** [neisbut/Npgsql.Bulk#48]
when we use an enum in our entity it generate a migration like this one

`
migrationBuilder.AlterDatabase().Annotation("Npgsql:Enum:myEnum1", "New,Submitted,Failed,AwaitingCapture")
     migrationBuilder.CreateTable(
                name: "mytable",
                columns: table => new
                {
                    payer_id = table.Column<myEnum1>()
                },
`

this will error
`
System.NotImplementedException: Column type 'myEnum1' is not supported
   at NpgsqlDbType Npgsql.Bulk.NpgsqlBulkUploader.GetNpgsqlType(ColumnInfo info)
   at List<MappingInfo> Npgsql.Bulk.NpgsqlBulkUploader.GetMappingInfo(Type type, string tableName)+(MappingInfo x) => { }
   at void System.Collections.Generic.List<T>.ForEach(Action<T> action)
   at List<MappingInfo> Npgsql.Bulk.NpgsqlBulkUploader.GetMappingInfo(Type type, string tableName)
   at EntityInfo Npgsql.Bulk.NpgsqlBulkUploader.CreateEntityInfo<T>()
   at EntityInfo Npgsql.Bulk.NpgsqlBulkUploader.GetEntityInfo<T>()+(string x) => { }
   at TValue System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.GetOrAdd(TKey key, Func<TKey, TValue> valueFactory)
   at EntityInfo Npgsql.Bulk.NpgsqlBulkUploader.GetEntityInfo<T>()
`
is there any way to map enum ? i've searched for enum in NpgsqlDbType but didn't found anything :/

**Comment by creste** [comment]
@neisbut - I also ran into this problem.  I noticed this was also reported in #29 but was closed due to inactivity.  In your reply at https://github.com/neisbut/Npgsql.Bulk/issues/29#issuecomment-513472439 you referenced the test project which verifies enums can be stored correctly.  I confirmed that the test project for DotNetStandard21Ef6 uses a DAL class called `Address` which has a public property called `Type` of type `AddressType?`:
https://github.com/neisbut/Npgsql.Bulk/blob/55819aa84242301a33dcc6ad5d38fb2fc3cec3dc/src/Npgsql.Bulk.SampleRunner/DAL/Address.cs#L28

The `AddressType` enum uses integers for the underlying value type:
https://github.com/neisbut/Npgsql.Bulk/blob/627005b2ca532537355c98efb952c8b9564b4fdc/src/Npgsql.Bulk.SampleRunner/DAL/AddressType.cs#L9-L16

If you generate a migration using the schema defined in in BulkContext at https://github.com/neisbut/Npgsql.Bulk/blob/dbf00015ea13b526f0047440d26f17e86cccc109/src/Npgsql.Bulk.SampleRunner/DAL/BulkContext.cs#L13-L20

then the EF6 migration file will define the `Type` field in postgres like this:
```csharp
type = c.Int(),
```
Notice how it is mapped to an integer in postgres.  If CLR enums are always mapped to built-in postgres types, like integers, then Npgsql.Bulk works correctly, as you stated in #29.  However, postgres also has it's own user-defined enum type, documented at https://www.postgresql.org/docs/current/datatype-enum.html.  Npgsql supports automatically mapping user-defined postgres enums to CLR enums, as documented at https://www.npgsql.org/doc/types/enums_and_composites.html.

The bug in Npgsql.Bulk is that when using Npgsql's automatic mapping for CLR enums to postgres enums, `NpgsqlBulkUploader.GetNpgsqlType()` throws an exception because it can't map a user-defined postgres type (e.g. "address_type") to the fixed list of types defined in NpgsqlDbTypes.  The exception is thrown here:
https://github.com/neisbut/Npgsql.Bulk/blob/c3339c66442cc1299771a73090d51fce97c7e615/src/Npgsql.Bulk/NpgsqlBulkUploader.cs#L148

One way to fix that problem is to use `NpgsqlConnection.TypeMapper.Mappings` to locate the CLR type that is mapped to the postgres type.  If the CLR type is an enum then it should be safe to assume that column can be automatically mapped to a postgres enum using Npgsql's built-in functionality.  In such cases, `NpgsqlBulkUploader.GetNpgsqlType()` can return `NpgsqlDbType.Unknown`.  Here's an example of such a code change:

```csharp
// Allow postgres enum types to be mapped to CLR enums
var clrType = RelationalHelper.GetNpgsqlConnection(context).TypeMapper.Mappings
    .FirstOrDefault(mapping => mapping.PgTypeName == info.ColumnType)?
    .ClrTypes
    .FirstOrDefault();
if (clrType != null && clrType.IsEnum)
{
    // NpgsqlDbType.Unknown is a dummy value.  The actual postgres type
    // will be determined later by Npgsql.
    return NpgsqlDbType.Unknown;
}

throw new NotImplementedException($"Column type '{info.ColumnType}' is not supported");
```

Making that change exposes another problem though.  In `NpgsqlBulkCodeBuilder.CreateWriterMethod` there are two places where MSIL is generated to call `NpgsqlBinaryImporter.Write(T, NpgsqlDbType)` (https://github.com/npgsql/npgsql/blob/8a479081f707784b5040747b23102c3d6371b9d3/src/Npgsql/NpgsqlBinaryImporter.cs#L183)

The first place is here:
https://github.com/neisbut/Npgsql.Bulk/blob/4ed2d86e03e778a82c9b4cf43a669853b5c5349a/src/Npgsql.Bulk/NpgsqlBulkCodeBuilder.cs#L266-L270

And the second place is here:
https://github.com/neisbut/Npgsql.Bulk/blob/4ed2d86e03e778a82c9b4cf43a669853b5c5349a/src/Npgsql.Bulk/NpgsqlBulkCodeBuilder.cs#L298-L302

In both cases, when a CLR enum has been mapped to a postgres enum then `NpbsqlDbType.Unknown` will be passed as the second parameter to `Write(T, NpgsqlDbType)`.  That is a problem because Npgsql needs to determine the postgres type using it's automatic mapping logic instead of trusting that the type is `NpgsqlDbType.Unknown`.  To fix that problem, `NpgsqlBulkCodeBuilder` needs to emit MSIL that calls `NpgsqlBulkCodeBuilder.writeMethodShort` which is already defined at:
https://github.com/neisbut/Npgsql.Bulk/blob/4ed2d86e03e778a82c9b4cf43a669853b5c5349a/src/Npgsql.Bulk/NpgsqlBulkCodeBuilder.cs#L35-L37

And instead of passing in the enumeration's underlying type it should just pass in the enumeration's type.  Here is an example of the modification that needs to be made in both cases:

```csharp
// If an enum's type is not known then assume Npgsql will map it to the
// correct postgres enum type.  If the CLR enum wasn't already registered
// with Npgsql then Npgsql will throw an exception with an informative
// error message.
if (info.NpgsqlType == NpgsqlTypes.NpgsqlDbType.Unknown)
{
     ilOut.Emit(OpCodes.Callvirt, writeMethodShort.MakeGenericMethod(fieldType.GetTypeInfo()));
}
else
{
     // Else, this CLR enum does not map to a postgres enum, so assume the
     // field type in postgres matches the CLR enum's underlying type,
     // e.g. "int".
     ilOut.Emit(OpCodes.Ldc_I4_S, (int)info.NpgsqlType);
     ilOut.Emit(OpCodes.Call, writeMethodFull.MakeGenericMethod(Enum.GetUnderlyingType(fieldType.GetTypeInfo())));
}
```

The above code needs to be modified slightly for the second case to handle the fact that `underlying != null`.

After making those changes and modifying the EFCore test projects to use mapped enums with Npgsql I am able to bulk insert both mapped enums and non-mapped enums using Npgsql.Bulk.

I am working on a pull request to show the full set of changes and hope to have that finished soon.

**Comment by neisbut** [comment]
Hi @creste , thanks a lot for such a detailed review and fix! Very appreciated! I will review and merge shortly!

**Comment by creste** [comment]
Thank you @neisbut!  I updated my projects to use version 0.8.3 and confirmed CLR enums now work fine.
